name: build and deploy nodejs

on:

  push:

    branches:  

       - main  

jobs:

  build:

    runs-on: ubuntu-latest




    steps:

      - uses: actions/checkout@v2

      - name: Use Node.js

        uses: actions/setup-node@v2

        with: 

          node-version: "12.x"

      - name: Install dependencies

        run: npm install




  deploy:

    name: Deploy to EC2 on master branch push

    needs: build

    runs-on: ubuntu-latest




    steps:

      - name: Checkout the files

        uses: actions/checkout@v2




      - name: Deploy to Server

        uses: easingthemes/ssh-deploy@main

        env:

          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}

          SOURCE: "/."

          REMOTE_HOST: ${{ secrets.HOST_DNS }}

          REMOTE_USER: ${{ secrets.USERNAME }}

          TARGET: ${{ secrets.TARGET_DIR }}
